### ISSUE TITLE
server.js fails to start

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/alicenode#3]
Running 'npm start' from ../alicenode: 
> alice_runtime@1.0.0 start /Users/mp/alicenode
> node start.js

server.js has started
[ '/usr/local/Cellar/node/9.7.1_1/bin/node',
  '/Users/mp/alicenode/server.js' ]
project_path /Users/mp/alicenode_inhabitat
editor_path /Users/mp/alicenode
client_path /Users/mp/alicenode/client

Rebuilt Repo Graph

mapped state.bin, size 80
server listening on 8080
Console()
1 monitor(s)
arg 0 /Users/mp/alicenode/alice
arg 1 project.dylib
setup
alice alice 0x1094fbec0
buffer.js:1015
    throw new errors.RangeError('ERR_INDEX_OUT_OF_RANGE');
    ^

RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Uint8Array.readUInt32LE (buffer.js:1079:5)
    at Uint8Array.Buffer.readFloatLE (buffer.js:1264:23)
    at Timeout._onTimeout (/Users/mp/alicenode/server.js:128:20)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
----------------------------------------------------------------------
server.js restarted due to:  undefined
[ '/usr/local/Cellar/node/9.7.1_1/bin/node',
  '/Users/mp/alicenode/server.js' ]
project_path /Users/mp/alicenode_inhabitat
editor_path /Users/mp/alicenode
client_path /Users/mp/alicenode/client
/Users/mp/alicenode/node_modules/nodemon/lib/monitor/match.js:136
  var rules = monitor.sort(function (a, b) {
                      ^

TypeError: Cannot read property 'sort' of undefined
    at match (/Users/mp/alicenode/node_modules/nodemon/lib/monitor/match.js:136:23)
    at FSWatcher.filterAndRestart (/Users/mp/alicenode/node_modules/nodemon/lib/monitor/watch.js:162:19)
    at FSWatcher.emit (events.js:127:13)
    at FSWatcher.<anonymous> (/Users/mp/alicenode/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/Users/mp/alicenode/node_modules/chokidar/index.js:241:5)
    at FSWatcher.<anonymous> (/Users/mp/alicenode/node_modules/chokidar/lib/fsevents-handler.js:206:14)
    at addOrChange (/Users/mp/alicenode/node_modules/chokidar/lib/fsevents-handler.js:212:7)
    at FSWatcher.<anonymous> (/Users/mp/alicenode/node_modules/chokidar/lib/fsevents-handler.js:244:16)
    at filteredListener (/Users/mp/alicenode/node_modules/chokidar/lib/fsevents-handler.js:60:7)
    at /Users/mp/alicenode/node_modules/chokidar/lib/fsevents-handler.js:85:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alice_runtime@1.0.0 start: `node start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alice_runtime@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mp/.npm/_logs/2018-04-03T18_42_46_712Z-debug.log

**Comment by grrrwaaa** [comment]
I see "mapped state.bin, size 80" which tells me something didn't update yet -- it should be size 120 now. (The first crash error is due to trying to read into state.bin beyond the 80 byte mark.)

Can you make sure that these have run completely:

```
cd ../alicenode_inhabitat
rm state.bin
git pull
./build.sh
```

And then try running alicenode again?

**Comment by michaelpalumbo** [comment]
Ok, so I did that, and now this is the error I'm receiving:

> alice_runtime@1.0.0 start /Users/mp/alicenode
> node start.js

server.js has started
[ '/usr/local/Cellar/node/9.7.1_1/bin/node',
  '/Users/mp/alicenode/server.js' ]
project_path /Users/mp/alicenode_inhabitat
editor_path /Users/mp/alicenode
client_path /Users/mp/alicenode/client
project lib is out of date, rebuilding
project.cpp:22:1: error: expected '}'
client updated project
^
project.cpp:17:20: note: to match this '{'
float vertices[] = {
                   ^
project.cpp:71:38: error: invalid application of 'sizeof' to an incomplete type 'float []'
        glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);
                                            ^~~~~~~~~~
project.cpp:132:50: error: invalid application of 'sizeof' to an incomplete type 'float []'
    glDrawArraysInstanced(GL_TRIANGLES, 0, sizeof(vertices) / (sizeof(float) * 3), NUM_OBJECTS);
                                                 ^~~~~~~~~~
3 errors generated.
ERROR Command failed: sh build.sh "/Users/mp/alicenode"
project.cpp:22:1: error: expected '}'
client updated project
^
project.cpp:17:20: note: to match this '{'
float vertices[] = {
                   ^
project.cpp:71:38: error: invalid application of 'sizeof' to an incomplete type 'float []'
        glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);
                                            ^~~~~~~~~~
project.cpp:132:50: error: invalid application of 'sizeof' to an incomplete type 'float []'
    glDrawArraysInstanced(GL_TRIANGLES, 0, sizeof(vertices) / (sizeof(float) * 3), NUM_OBJECTS);
                                                 ^~~~~~~~~~
3 errors generated.


Rebuilt Repo Graph

failed to map the state.bin: ENOENT: no such file or directory, stat 'state.bin'
server listening on 8080
Console()
1 monitor(s)
arg 0 /Users/mp/alicenode/alice
arg 1 project.dylib
setup
alice alice 0x10ceb5ec0
New framebuffer resolution 1920x1280
Loaded OpenGL 4.1

OpenGL 4.1 ATI-1.51.8, GLSL 4.10
Console()
onload
sim alice 0x10ceb5ec0
mmap state.bin of size 80
file state.bin is size 0
file state.bin is size 80
mmap state.bin of size 80
file state.bin is size 80
file state.bin is size 80
sim state 0x115e9e000 should be size 80
initialized
shader loading test.vert.glsl test.frag.glsl
ok
shader loaded 0x7f8253225310
init result 0
File /Users/mp/alicenode_inhabitat/.DS_Store has been changed

**Comment by michaelpalumbo** [comment]
Right. I had actually reset my local HEAD, but had forgotten than I accidentally pushed the project.cpp version with conflict markers. I decided to just clone the repo again, ran npm install, ran build.sh, and yet continued to receive the same error.

**Comment by grrrwaaa** [comment]
Did you fresh clone alicenode_inhabitat?

**Comment by michaelpalumbo** [comment]
No only alicenode. I'll fresh clone alicenode_inhabitat tomorrow and get back to you.

Thanks!

**Comment by michaelpalumbo** [comment]
Hi Graham, it works now, did the following:

fresh clone of alicenode_inhabitat
pulled your recent changes to alicenode
ran ./build.sh
ran npm start
