### ISSUE TITLE
generated warnings from alice.cpp during npm install on ~/alicenode

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/alicenode#5]
build [object Object] error [object Object]
In file included from src/alice.cpp:12:
include/al/al_kinect2.h:156:2: warning: control may reach end of non-void function [-Wreturn-type]
        }
        ^
src/alice.cpp:98:15: warning: unused variable 'c' [-Wunused-variable]
        static float c = 1;
                     ^
2 warnings generated.

**Comment by grrrwaaa** [comment]
should be fixed now
