### ISSUE TITLE
filewatcher is reporting changes made to .git object directory

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/alicenode#7]
shouldn't be this way, as it could cause loops since a commit is made whenever a file in the actual repo is changed

source of this error is in alice.cpp, line 305, "Change detected in [filename]." how do we restrict the directory scope in cpp so we don't track the .git meta folder?

**Comment by grrrwaaa** [comment]
A: The alice.cpp filewatcher is 'read only' -- it's only reporting that a file changed, but not changing anything itself, so it shouldn't cause a commit loop. 

But maybe it would be helpful to suppress the console message, since it is distracting. Hopefully that's checked in now.

**Comment by michaelpalumbo** [comment]
Thanks Graham, looks good!
